[global]
strict init = true
buffer min  = 1024
buffer max  = 2MB
rotate lock file = /tmp/zlog.lock
default format = "%d(%F %X).%msms %-6V %c[%p](%f:%U():%L) - %m"

[formats]
null      = ""
print     = "%m"
simple    = "%d(%F %X) %-6V (%f:%U():%L) - %m"
normalms  = "%d(%F %X).%msms %-6V %c[%p](%f:%U():%L) - %m"
normalus  = "%d(%F %X).%usus %-6V %c[%p](%f:%U():%L) - %m"
complexms = "%d(%F %X).%msms %-6V %H %c[%p:%t](%f:%U():%L) - %m"
complexus = "%d(%F %X).%usms %-6V %H %c[%p:%t](%f:%U():%L) - %m"

# %n = \n
# %f = file
# %F = absolute path file

mdc_format = "%d(%F %X).%msms %-6V %c[%p](%f:%U():%L) [%M(myMDC)] - %m"

[rules]
*.*        >stdout;
#*.*        >stderr;
#!.*        >stderr;

#*.debug    >stderr;
#*.=debug   >stderr;
#*.!debug   >stderr;

#*.info     >stderr;
#*.notice   >stderr;
#*.warn     >stderr;
#*.error    >stderr;
#*.fatal    >stderr;

#*.*        >stderr;simple
#*.*        >stderr;normalms
#*.*        >stderr;complexms
#*.*        >stderr;mdc_format

#*.*        "./aa.%d(%F).log";
#*.*        "./aa.%d(%F).log";normalms
#*.*        -"./aa.%d(%F).log";
#*.*        "./aa.log", 1KB * 5;
#*.*        "./aa.log", 10MB * 5;
#*.*        "./aa.log", 10MB * 5;normalms
